# Generated by Django 4.2.19 on 2025-03-15 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.CharField(max_length=255)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("status", models.BooleanField(default=False)),
                ("device_id", models.IntegerField(blank=True, null=True)),
                (
                    "device_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "action",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("on", "On"),
                            ("off", "Off"),
                            ("open", "Open"),
                            ("close", "Close"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("user_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.user"
                    ),
                ),
            ],
        ),
    ]
