# Generated by Django 4.2.19 on 2025-03-15 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="action",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="device_id",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="device_name",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="user_name",
        ),
    ]
