# Generated by Django 4.2.19 on 2025-03-15 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("roomname", models.CharField(max_length=50)),
                ("createdat", models.DateTimeField(auto_now_add=True)),
                ("description", models.TextField()),
            ],
        ),
    ]
