# Generated by Django 4.2.19 on 2025-03-15 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("rooms", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("devicename", models.CharField(max_length=50)),
                ("devicetype", models.CharField(max_length=50)),
                ("createdat", models.DateTimeField(auto_now_add=True)),
                ("description", models.TextField()),
                ("status", models.BooleanField(default=True)),
                (
                    "roomid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="rooms.room"
                    ),
                ),
            ],
        ),
    ]
