# Generated by Django 4.2.19 on 2025-03-18 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0002_alter_device_roomid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="devicetype",
            field=models.CharField(
                choices=[("light", "Light"), ("fan", "Fan"), ("door", "Door")],
                max_length=10,
            ),
        ),
    ]
