# Generated by Django 4.2.19 on 2025-03-18 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0003_alter_device_devicetype"),
    ]

    operations = [
        migrations.CreateModel(
            name="Temperature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("temperature", models.FloatField()),
                ("createdat", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
