# Generated by Django 4.2.19 on 2025-03-15 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Username", models.CharField(max_length=50)),
                ("CreatedAt", models.DateTimeField(auto_now_add=True)),
                ("Password", models.CharField(max_length=50)),
                ("FullName", models.CharField(max_length=50)),
                ("Email", models.EmailField(max_length=254, unique=True)),
                ("Status", models.BooleanField(default=True)),
                ("Phone", models.CharField(max_length=50)),
                ("Role", models.CharField(max_length=50)),
            ],
        ),
    ]
