# Generated by Django 5.1.7 on 2025-04-07 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='GoogleCredential',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='Phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
