# Generated by Django 4.2.19 on 2025-03-18 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="CreatedAt",
            new_name="createdat",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="Email",
            new_name="email",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="FullName",
            new_name="fullname",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="Password",
            new_name="password",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="Phone",
            new_name="phone",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="Role",
            new_name="role",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="Status",
            new_name="status",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="Username",
            new_name="username",
        ),
    ]
